Update mali_osk_time.c
LibreELEC/mali-utgard pull request #2
Opened 2020-04-03 20:02 UTC by devegoo

Hi. I don't know is this 100% correct, but this changes resolved problem when im compiled libreelec for mali mali-utgard 450 , before i have break and error on kernel 5.6-rc6

2020-04-05 14:16 UTC, jernejsk commented on driver/src/devicedrv/mali/linux/mali_osk_time.c
> +	return timespec64_to_ns;
Was this even build tested? you need `()` at the end, otherwise you would return function pointer. Same below.

2020-04-05 14:23 UTC, devegoo commented
Maybe . H264 works in hw mode

2020-04-05 14:26 UTC, devegoo commented
blinking Red plane on some formats >sd in SW mode

2020-04-05 15:19 UTC, jernejsk commented
well, make it compile and make it properly work are not the same thing.

2020-04-05 15:24 UTC, jernejsk requested changes

2020-04-05 15:24 UTC, jernejsk commented on driver/src/devicedrv/mali/linux/mali_osk_time.c
> +	return ktime_get_boottime_ns;
```suggestion
	return ktime_get_boottime_ns();
```

2020-04-05 15:24 UTC, jernejsk commented on driver/src/devicedrv/mali/linux/mali_osk_time.c
> +	return timespec64_to_ns;
```suggestion
	struct timespec64 ts64;
	ktime_get_real_ts64(&ts64);
	return timespec64_to_ns(&ts64);
```

2020-04-05 15:24 UTC, jernejsk commented on driver/src/devicedrv/mali/linux/mali_osk_time.c
> +	return ktime_get_boottime_ns;
Please test both suggested changes. If they work, accept them.

2020-04-05 16:06 UTC, devegoo commented
Already started new libreelec - make image - with mali as driver but compilation take a little bit of time. I will do report here if i finish. I merge your proposed changes at time ... Because i not prefetch packages.

2020-04-06 09:44 UTC, devegoo commented
Hi. Compillation with changes proposed by you was succesfull and some formats /h.264 included in my build works good in hw mode , h.264 is only one format which have enabled hw in ffmpeg by now for Amlogic. Thank you.

2020-04-06 16:09 UTC, jernejsk commented
Just to make sure, you know that mali GPU is only for rendering and not video decoding, right?

2020-04-06 17:00 UTC, devegoo commented
Ok , now i know , i'm not expert with that... some bug in playing in sw mode exist if it is related , but probably it's some missing functions from kodi player in branch i'm used, i'm only want to try how this will be with mali as driver.

2020-04-07 03:05 UTC, chewitt approved these changes

2020-04-07 03:07 UTC, merged